# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run ng -- deploy joaopedro61-github-io --base-href=/joaopedro61.github.io/ --name=JoaoPedro61 --email=mjoaopedro61@gmail.com --no-silent --repo=https://JoaoPedro61:${{ secrets.GITHUB_TOKEN }}@github.com/JoaoPedro61/joaopedro61.github.io.git
